#!/bin/bash

GIT_DIR=/home/deploy/repo
WORK_TREE=/home/deploy/source

git --work-tree=$WORK_TREE --git-dir=$GIT_DIR checkout -f

cd "$WORK_TREE/source/client/"
npm install
bower install
export NODE_ENV=production; gulp production

cd "$WORK_TREE/source/server/"
npm install
pm2 restart server.js                                    
